import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRef, useState } from "react";
import dynamic from "next/dynamic";
const ReactPlayer = dynamic(() => import("react-player/lazy"), { ssr: false });

export default function Home() {
  const player = useRef();
  const [toggle, setToggle] = useState(false)

  const currTimeUpdated = () => {
    //const currTime = player.current.getCurrentTime()       //////// this does not work
    //console.log('current time is: ' + currTime)
    if (toggle) {
      console.log('toggle is set')
    }
    else {
      console.log('toggle is not set')
    }
  }

  const skip = () => {
    seekTo(player.current.getCurrentTime() + 10, 'seconds')  /////// this does not work
  }

  const playerElement = <ReactPlayer url='https://www.youtube.com/watch?v=ysz5S6PUM-U'
    ref={player}
    controls={true}      
    onProgress={currTimeUpdated}
  />
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {playerElement}
        <button onClick={() => setToggle(!toggle)}>
          {'toggle is ' + toggle}
        </button>
        <button onClick={skip}>
          Skip ahead 10 seconds
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
